### PR TITLE
Make signature pad unscrollable when sign

### PR DESCRIPTION
**Pull request by tony123S**
Fix https://github.com/kiwi-bop/flutter_signature_pad/issues/10

### CODE REVIEW

**Comment by jaumard** [comment]
Hello, thanks for the PR, I was wondering why it's all green in the diff, quite hard to check what you changed as it consider you change everything

**Comment by tony123S** [comment]
> Hello, thanks for the PR, I was wondering why it's all green in the diff, quite hard to check what you changed as it consider you change everything

I'm sorry, I still new to this. Should I close it and create a new one?

**Comment by jaumard** [comment]
Let's try this yes see if it's better, it's the first time I see this problem 
Thanks

**Comment by tony123S** [comment]
I follow this https://yangsu.github.io/pull-request-tutorial/ to create a new pull request, but get this error:

```

remote: Permission to kiwi-bop/flutter_signature_pad.git denied to tony123S.
fatal: unable to access 'https://github.com/kiwi-bop/flutter_signature_pad.git/': The requested URL returned error: 403
```

**Comment by jaumard** [comment]
You miss the first point `Pull Request from a forked repository` you need to fork the repository first.
For that click Fork on the top right on this page:  
Capture d’écran 2020-03-17 à 11 03 31

**Comment by tony123S** [comment]
@jaumard  my bad. Was able to create a new PR.

**Pull request closed without merging**
